In [26]:

import numpy as np 
import pandas as pd 
import pandas  as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import os
warnings.filterwarnings('ignore')

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/default/default.xlsx


In [27]:
import pandas  as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [28]:
df1=pd.read_excel('../input/default/default.xlsx')
df=df1.copy()

In [29]:
pd.to_datetime(df['DATE_DE_CREATION_TIERS'],format='%D%M%Y')
pd.to_datetime(df['DATE_DE_CREATION_ENTREP'],format='%D%M%Y')
df.drop('numtiers',axis=1,inplace=True)
df.drop('Annee',axis=1,inplace=True)
df.set_index('NUMTIERS_ANNEE')

defaut DATE_DE_CREATION_TIERS DATE_DE_CREATION_ENTREP  \
NUMTIERS_ANNEE                                                              
5200000007513_2015       0             2008-01-02              1982-01-05   
5200000007513_2016       0             2008-01-02              1982-01-05   
5200000007934_2015       0             1988-05-31              1953-08-05   
5200000007934_2017       0             1988-05-31              1953-08-05   
5200000008051_2015       0             1998-10-02              1995-05-22   
...                    ...                    ...                     ...   
5200008692041_2019       0             2016-02-25              2012-11-28   
5200008791992_2016       0             2015-09-14              2015-08-25   
5200007684315_2018       1             2013-01-09              2013-02-28   
5200007955060_2019       1             2013-10-09              2006-08-31   
5200008030705_2015       1             2013-12-30              1990-12-21   

                    CHIFFRE_AFFAIRES  EXCEDENT_BRUT_EXPLOITATION  \
NUMTIERS_ANNEE                                                     
5200000007513_2015      2.360732e+08                8.258202e+06   
5200000007513_2016      2.583866e+08                4.107269e+06   
5200000007934_2015      2.024265e+08                5.028465e+06   
5200000007934_2017      2.109176e+08                1.307649e+07   
5200000008051_2015      1.719875e+08                1.614263e+07   
...                              ...                         ...   
5200008692041_2019      2.126070e+08                3.447732e+06   
5200008791992_2016      1.899246e+08                1.155362e+06   
5200007684315_2018      2.878672e+09                1.283697e+09   
5200007955060_2019      4.843269e+08                3.825166e+07   
5200008030705_2015      3.247440e+08                1.945273e+07   

                    RESULTAT_EXPlOITATION  RESULTAT_NET  \
NUMTIERS_ANNEE                                            
5200000007513_2015           7.120503e+06 -1.404038e+07   
5200000007513_2016           2.031312e+06  2.312467e+06   
5200000007934_2015           3.602226e+06 -4.132730e+05   
5200000007934_2017           1.251423e+07  7.501947e+06   
5200000008051_2015           1.254485e+07  1.401029e+06   
...                                   ...           ...   
5200008692041_2019           3.064909e+06  5.818412e+05   
5200008791992_2016           1.154164e+06  4.472306e+05   
5200007684315_2018           9.366426e+08  5.850665e+08   
5200007955060_2019           1.351372e+07 -5.124705e+06   
5200008030705_2015           8.007130e+06  2.445125e+06   

                    FINANCEMENT_PERMANENT  FONDS_DE_ROULEMENT  \
NUMTIERS_ANNEE                                                  
5200000007513_2015           9.867039e+07        8.151958e+07   
5200000007513_2016           9.861561e+07        9.572609e+07   
5200000007934_2015           2.578635e+07        2.529267e+07   
5200000007934_2017           4.363634e+07        4.355634e+07   
5200000008051_2015           5.518648e+07        5.508778e+07   
...                                   ...                 ...   
5200008692041_2019           9.025440e+06        8.961776e+06   
5200008791992_2016           6.713914e+05        6.713914e+05   
5200007684315_2018           5.479125e+09        5.469125e+09   
5200007955060_2019           3.007445e+08        2.955590e+08   
5200008030705_2015           7.474035e+07        7.468395e+07   

                    BESOIN_FONDS_ROULEMENT  ...  \
NUMTIERS_ANNEE                              ...   
5200000007513_2015            1.099038e+08  ...   
5200000007513_2016            1.251023e+08  ...   
5200000007934_2015            1.686528e+07  ...   
5200000007934_2017            3.864704e+07  ...   
5200000008051_2015            1.029947e+08  ...   
...                                    ...  ...   
5200008692041_2019            1.275252e+07  ...   
5200008791992_2016           -1.075918e+06  ...   
520000768

In [30]:
df['DIVERSITE_CLIENTS'].replace("Diversification tres forte par produits, clients, situation geographique",'Diversification trés forte par produits, clients, situation geographique',inplace=True)
df['DIVERSITE_FOURNISSEURS'].replace('Tres grande diversite','Très grande diversite',inplace=True)
df['DIVERSITE_FOURNISSEURS'].replace('Trés grande diversite','Très grande diversite',inplace=True)
df['REPUTATION'].replace('Tres bonne','Très bonne',inplace=True)
df['NIVEAU_COMPETITIVITE'].replace('Tres forte concurrence','Très forte concurrence',inplace=True)

df['IMPACT_SOCIAUX_ENVIRONNEMENTAL'].replace('Aucun impact social ou environnemental, soumis e une reglementation','Aucun impact social ou environnemental, soumis à une reglementation',inplace=True)
    
    

In [31]:
categories_features=[]
numeric_features=[]
time_series_features=[]
for feature in df.columns:
    if df[feature].dtype=='O':
        categories_features.append(feature)
    elif  (df[feature].dtype in('int64',"float64")) and (feature!='defaut'):
        numeric_features.append(feature)
    else:
        time_series_features.append(feature)
print(len(categories_features),'///',len(numeric_features),'///',len(time_series_features))

13 /// 22 /// 3


In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le_count = 0
for col in categories_features:
    if len(set(df[col])) <= 4:
        le.fit(df[col].dropna())
        df[col] = le.transform(df[col])
        le_count += 1
            
print('%d columns were label encoded.' % le_count)

7 columns were label encoded.


In [8]:
target=df['defaut']
df.drop('defaut',inplace=True,axis=1)

In [9]:
import featuretools as ft
es=ft.EntitySet(id='default')
es = es.add_dataframe(
    dataframe_name="default",
    dataframe=df,
        index="NUMTIERS_ANNEE",

)

es

Entityset: default
  DataFrames:
    default [Rows: 1521, Columns: 37]
  Relationships:
    No relationships

In [10]:
feature_matrix, feature_defs = ft.dfs(
    entityset=es,
    target_dataframe_name="default",
    agg_primitives=['entropy',"count",'mean','mode'],
    trans_primitives=['divide_numeric'],
    max_depth=5,
)
feature_matrix

CHIFFRE_AFFAIRES  EXCEDENT_BRUT_EXPLOITATION  \
NUMTIERS_ANNEE                                                     
5200000007513_2015      2.360732e+08                8.258202e+06   
5200000007513_2016      2.583866e+08                4.107269e+06   
5200000007934_2015      2.024265e+08                5.028465e+06   
5200000007934_2017      2.109176e+08                1.307649e+07   
5200000008051_2015      1.719875e+08                1.614263e+07   
...                              ...                         ...   
5200008692041_2019      2.126070e+08                3.447732e+06   
5200008791992_2016      1.899246e+08                1.155362e+06   
5200007684315_2018      2.878672e+09                1.283697e+09   
5200007955060_2019      4.843269e+08                3.825166e+07   
5200008030705_2015      3.247440e+08                1.945273e+07   

                    RESULTAT_EXPlOITATION  RESULTAT_NET  \
NUMTIERS_ANNEE                                            
5200000007513_2015           7.120503e+06 -1.404038e+07   
5200000007513_2016           2.031312e+06  2.312467e+06   
5200000007934_2015           3.602226e+06 -4.132730e+05   
5200000007934_2017           1.251423e+07  7.501947e+06   
5200000008051_2015           1.254485e+07  1.401029e+06   
...                                   ...           ...   
5200008692041_2019           3.064909e+06  5.818412e+05   
5200008791992_2016           1.154164e+06  4.472306e+05   
5200007684315_2018           9.366426e+08  5.850665e+08   
5200007955060_2019           1.351372e+07 -5.124705e+06   
5200008030705_2015           8.007130e+06  2.445125e+06   

                    FINANCEMENT_PERMANENT  FONDS_DE_ROULEMENT  \
NUMTIERS_ANNEE                                                  
5200000007513_2015           9.867039e+07        8.151958e+07   
5200000007513_2016           9.861561e+07        9.572609e+07   
5200000007934_2015           2.578635e+07        2.529267e+07   
5200000007934_2017           4.363634e+07        4.355634e+07   
5200000008051_2015           5.518648e+07        5.508778e+07   
...                                   ...                 ...   
5200008692041_2019           9.025440e+06        8.961776e+06   
5200008791992_2016           6.713914e+05        6.713914e+05   
5200007684315_2018           5.479125e+09        5.469125e+09   
5200007955060_2019           3.007445e+08        2.955590e+08   
5200008030705_2015           7.474035e+07        7.468395e+07   

                    BESOIN_FONDS_ROULEMENT  CAPITAUX_PROPRES  TRESORIE_NETTE  \
NUMTIERS_ANNEE                                                                 
5200000007513_2015            1.099038e+08      9.448769e+07   -2.838425e+07   
5200000007513_2016            1.251023e+08      9.680015e+07   -2.937622e+07   
5200000007934_2015            1.686528e+07      2.578635e+07    8.427388e+06   
5200000007934_2017            3.864704e+07      4.363634e+07    4.909299e+06   
5200000008051_2015            1.029947e+08      5.100284e+07   -4.790696e+07   
...                                    ...               ...             ...   
5200008692041_2019            1.275252e+07      9.025440e+06   -3.790747e+06   
5200008791992_2016           -1.075918e+06      6.713914e+05    1.747309e+06   
5200007684315_2018            5.342844e+09      3.166397e+09    1.262810e+08   
5200007955060_2019            6.038014e+08      2.481153e+08   -3.082424e+08   
5200008030705_2015            9.807616e+07      4.657197e+07   -2.339222e+07   

                     TOTAL_BILAN  ...  TRESORIE_NETTE / POSITIONNEMENTMARCHE  \
NUMTIERS_ANNEE                    ...                                          
5200000007513_2015  1.983873e+08  ...                                   -inf   
5200000007513_2016  2.061276e+08  ...                                   -inf   
5200000007934_2015  7.541207e+07  ...                           2.809129e+06   
5200000007934_2017  6.840979e+07  ...                                    inf   


In [11]:
feature_matrix=pd.get_dummies(feature_matrix)

In [12]:
for feature in feature_matrix.columns:
    if (feature_matrix[feature].isna().sum()/1521)>0.2:
        feature_matrix.drop(feature,axis=1,inplace=True)
feature_matrix.replace(np.inf,0.00001,inplace=True)
feature_matrix.replace(-np.inf,0.00001,inplace=True)
feature_matrix.replace(np.nan,0.00001,inplace=True)
feature_matrix.replace(0,0.00001,inplace=True)

In [13]:
import pandas as pd
import numpy as np

def clean_dataset(df):
    assert isinstance(df, pd.DataFrame)
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [14]:
feature_matrix=clean_dataset(feature_matrix)

In [15]:
feature_matrix.select_dtypes('O').columns

Index([], dtype='object')

In [16]:
feature_matrix.index=feature_matrix.index.astype('int')
feature_matrix=feature_matrix.astype('float64')

In [17]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer()
imputer.fit_transform(feature_matrix)

array([[2.36073240e+08, 8.25820171e+06, 7.12050300e+06, ...,
        1.00000000e-05, 1.00000000e-05, 1.00000000e+00],
       [2.58386615e+08, 4.10726885e+06, 2.03131193e+06, ...,
        1.00000000e-05, 1.00000000e-05, 1.00000000e+00],
       [2.02426475e+08, 5.02846460e+06, 3.60222577e+06, ...,
        1.00000000e-05, 1.00000000e-05, 1.00000000e-05],
       ...,
       [2.87867198e+09, 1.28369715e+09, 9.36642623e+08, ...,
        1.00000000e-05, 1.00000000e-05, 1.00000000e-05],
       [4.84326912e+08, 3.82516601e+07, 1.35137178e+07, ...,
        1.00000000e-05, 1.00000000e-05, 1.00000000e-05],
       [3.24744030e+08, 1.94527341e+07, 8.00713021e+06, ...,
        1.00000000e-05, 1.00000000e-05, 1.00000000e-05]])

In [18]:
from sklearn.decomposition import PCA
transformer = PCA(n_components=10)
X_transformed = transformer.fit_transform(feature_matrix.values)
np.sort(transformer.explained_variance_ratio_)

array([2.85609814e-08, 5.79425409e-08, 7.74599218e-08, 1.04582178e-07,
       1.48544896e-07, 1.93469597e-07, 7.27565181e-07, 1.64584526e-06,
       1.69050237e-05, 9.99979958e-01])

In [19]:
X=pd.DataFrame(X_transformed)

In [20]:
X['defaut']=list(target)

In [21]:
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
# setting up testing and training sets
X_train, X_test, y_train, y_test = train_test_split(X.iloc[:,0:2], X['defaut'], test_size=0.25, random_state=27)

# concatenate our training data back together
df_train = pd.concat([X_train, y_train], axis=1)

# Separate majority and minority classes
df_majority = df_train[df_train.defaut==0]
df_minority = df_train[df_train.defaut==1]

# oversample minority class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,    
                                 n_samples=len(df_majority),   
                                 random_state=1234) 
 

df_upsampled = pd.concat([df_majority, df_minority_upsampled])

df_upsampled.defaut.value_counts()


0    1099
1    1099
Name: defaut, dtype: int64

In [22]:
X_train=df_upsampled.drop('defaut',axis=1)
y_train=df_upsampled['defaut']

In [23]:
len(y_test[y_test==0])

369

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis,LinearDiscriminantAnalysis
from sklearn.metrics import roc_auc_score,f1_score,confusion_matrix,classification_report
RF=RandomForestClassifier()
QDE=QuadraticDiscriminantAnalysis()
LDA=LinearDiscriminantAnalysis()
RF.fit(X_train,y_train)
y_pred=RF.predict(X_test)
f1=f1_score(y_pred,y_test,average='weighted')
print('%.5f' %f1)
print(confusion_matrix(y_pred,y_test))

0.96110
[[363  11]
 [  6   1]]


In [25]:
roc_auc_score(y_pred,y_test,average='weighted')


0.5567226890756302